/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.sistema.view;

import br.com.sistema.dao.VagaDAO;
import br.com.sistema.dao.OrganizacaoDAO;
import br.com.sistema.model.Vaga;
import br.com.sistema.model.Organizacao;

import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Isabel
 */
public class FrmVaga extends javax.swing.JFrame {

    private VagaDAO dao = new VagaDAO();
    private OrganizacaoDAO organizacaoDAO = new OrganizacaoDAO();

    private int idSelecionado = 0;

    /**
     * Creates new form FrmVaga
     */
    public FrmVaga() {
        initComponents();

        tabelaVagas.setEnabled(true);
        tabelaVagas.setRowSelectionAllowed(true);
        tabelaVagas.setSelectionMode(
                ListSelectionModel.SINGLE_SELECTION
        );

        carregarOrganizacoes();
        carregarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        txtDescricao = new javax.swing.JTextField();
        txtCargaHoras = new javax.swing.JTextField();
        txtNumeroVagas = new javax.swing.JTextField();
        txtData = new javax.swing.JTextField();
        cmbStatus = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaVagas = new javax.swing.JTable();
        cmbOrganizacao = new javax.swing.JComboBox<>();
        btnSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jTextField1.setText("CADASTRO DE VAGAS");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("TITULO: ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("DESCRIÇÃO: ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("CARGA HORAS:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("NUMERO VAGAS:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("DATA: ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("STATUS: ");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("ID ORG: ");

        txtTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTituloActionPerformed(evt);
            }
        });

        cmbStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbStatusActionPerformed(evt);
            }
        });

        btnSalvar.setText("SALVAR");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnEditar.setText("EDITAR");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluir.setText("EXCLUIR");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnLimpar.setText("LIMPAR");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        tabelaVagas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "TITULO", "DESCRICAO", "CARGA HORAS", "NUMERO VAGAS", "DATA", "STATUS", "ID ORG"
            }
        ));
        tabelaVagas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaVagasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaVagas);

        cmbOrganizacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnSair.setText("Sair ->");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 294, Short.MAX_VALUE)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(168, 168, 168)
                                .addComponent(btnSair))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3))
                                        .addGap(37, 37, 37)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtCargaHoras, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
                                            .addComponent(txtDescricao)
                                            .addComponent(txtTitulo)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5))
                                        .addGap(28, 28, 28)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtNumeroVagas, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
                                            .addComponent(txtData)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cmbStatus)
                                            .addComponent(cmbOrganizacao, 0, 441, Short.MAX_VALUE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                                    .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(35, 35, 35))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSair)
                                .addGap(12, 12, 12)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtCargaHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtNumeroVagas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addComponent(jLabel6)))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(cmbOrganizacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void txtTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloActionPerformed

    private void cmbStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbStatusActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        try {

            String titulo = txtTitulo.getText().trim();
            String descricao = txtDescricao.getText().trim();
            String cargaH = txtCargaHoras.getText().trim();
            String numeroVagas = txtNumeroVagas.getText().trim();
            String data = txtData.getText().trim();
            String status = cmbStatus.getText().trim();

            String nomeOrganizacao
                    = (String) cmbOrganizacao.getSelectedItem();

            // Validação
            if (titulo.isEmpty()
                    || descricao.isEmpty()
                    || cargaH.isEmpty()
                    || numeroVagas.isEmpty()
                    || data.isEmpty()
                    || status.isEmpty()
                    || nomeOrganizacao == null
                    || nomeOrganizacao.trim().isEmpty()) {

                JOptionPane.showMessageDialog(this,
                        "Preencha todos os campos!");

                return;
            }

            int cargaHoras = Integer.parseInt(cargaH);
            int numeroVaga = Integer.parseInt(numeroVagas);

            // Busca o ID da organização pelo nome selecionado
            int idOrganizacao = buscarIdOrganizacao(nomeOrganizacao);

            if (idOrganizacao == 0) {

                JOptionPane.showMessageDialog(this,
                        "Organização não encontrada!");

                return;
            }

            // Converte a data
            SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
            formato.setLenient(false);
            java.util.Date dataVaga = formato.parse(data);

            // Cria a vaga
            Vaga vaga = new Vaga();

            vaga.setTitulo(titulo);
            vaga.setDescricao(descricao);
            vaga.setCargahoras(cargaHoras);
            vaga.setNumerovagas(numeroVaga);
            vaga.setDatavaga(dataVaga);
            vaga.setStatus(status);
            vaga.setIdOrganizacao(idOrganizacao);

            // Salva
            dao.salvar(vaga);

            JOptionPane.showMessageDialog(this,
                    "Vaga cadastrada com sucesso!");

            carregarTabela();
            limparCampos();

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(this,
                    "Carga horária e número de vagas devem ser números!");

        } catch (ParseException e) {

            JOptionPane.showMessageDialog(this,
                    "Data inválida! Digite no formato dd/MM/yyyy.");

        } catch (SQLException e) {

            JOptionPane.showMessageDialog(this,
                    "Erro ao salvar vaga:\n"
                    + e.getMessage());
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        try {

            if (idSelecionado == 0) {

                JOptionPane.showMessageDialog(this,
                        "Selecione uma vaga na tabela para editar!");

                return;
            }

            String titulo = txtTitulo.getText().trim();
            String descricao = txtDescricao.getText().trim();
            String cargaH = txtCargaHoras.getText().trim();
            String numeroVagas = txtNumeroVagas.getText().trim();
            String data = txtData.getText().trim();
            String status = cmbStatus.getText().trim();

            String nomeOrganizacao = (String) cmbOrganizacao.getSelectedItem();

            // Validação
            if (titulo.isEmpty()
                    || descricao.isEmpty()
                    || cargaH.isEmpty()
                    || numeroVagas.isEmpty()
                    || data.isEmpty()
                    || status.isEmpty()
                    || nomeOrganizacao == null
                    || nomeOrganizacao.trim().isEmpty()) {

                JOptionPane.showMessageDialog(this,
                        "Preencha todos os campos!");

                return;
            }

            int cargaHoras = Integer.parseInt(cargaH);
            int numeroVaga = Integer.parseInt(numeroVagas);

            // Busca o ID da organização pelo nome
            int idOrganizacao = buscarIdOrganizacao(nomeOrganizacao);

            if (idOrganizacao == 0) {

                JOptionPane.showMessageDialog(this,
                        "Organização não encontrada!");

                return;
            }

            SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
            formato.setLenient(false);
            java.util.Date dataVaga = formato.parse(data);

            // Cria a vaga
            Vaga vaga = new Vaga();

            vaga.setId(idSelecionado);
            vaga.setTitulo(titulo);
            vaga.setDescricao(descricao);
            vaga.setCargahoras(cargaHoras);
            vaga.setNumerovagas(numeroVaga);
            vaga.setDatavaga(dataVaga);
            vaga.setStatus(status);
            vaga.setIdOrganizacao(idOrganizacao);

            dao.editar(vaga);

            JOptionPane.showMessageDialog(this,
                    "Vaga editada com sucesso!");

            carregarTabela();
            limparCampos();

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(this,
                    "Carga horária e número de vagas devem ser números!");

        } catch (ParseException e) {

            JOptionPane.showMessageDialog(this,
                    "Data inválida! Digite no formato dd/MM/yyyy.");

        } catch (SQLException e) {

            JOptionPane.showMessageDialog(this,
                    "Erro ao editar vaga:\n"
                    + e.getMessage());
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        try {

            if (idSelecionado == 0) {

                JOptionPane.showMessageDialog(this,
                        "Selecione uma vaga na tabela para excluir!");

                return;
            }

            int resposta = JOptionPane.showConfirmDialog(
                    this,
                    "Deseja realmente excluir esta vaga?",
                    "Confirmar exclusão",
                    JOptionPane.YES_NO_OPTION
            );

            if (resposta == JOptionPane.YES_OPTION) {
                dao.excluir(idSelecionado);

                JOptionPane.showMessageDialog(this,
                        "Vaga excluída com sucesso!");

                carregarTabela();
                limparCampos();
            }

        } catch (SQLException e) {

            JOptionPane.showMessageDialog(this,
                    "Erro ao excluir vaga:\n"
                    + e.getMessage());
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        limparCampos();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void tabelaVagasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaVagasMouseClicked
        int linha = tabelaVagas.getSelectedRow();

        if (linha >= 0) {

            idSelecionado = Integer.parseInt(
                    tabelaVagas.getValueAt(linha, 0).toString()
            );

            txtTitulo.setText(
                    tabelaVagas.getValueAt(linha, 1).toString()
            );

            txtDescricao.setText(
                    tabelaVagas.getValueAt(linha, 2).toString()
            );

            txtCargaHoras.setText(
                    tabelaVagas.getValueAt(linha, 3).toString()
            );

            txtNumeroVagas.setText(
                    tabelaVagas.getValueAt(linha, 4).toString()
            );

            txtData.setText(
                    tabelaVagas.getValueAt(linha, 5).toString()
            );

            cmbStatus.setText(
                    tabelaVagas.getValueAt(linha, 6).toString()
            );

            int idOrganizacao = Integer.parseInt(tabelaVagas.getValueAt(linha, 7).toString());

            selecionarOrganizacao(idOrganizacao);
        }
    }//GEN-LAST:event_tabelaVagasMouseClicked

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        FrmMenu menu = new FrmMenu();
        menu.setLocationRelativeTo(this);
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmVaga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmVaga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmVaga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmVaga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmVaga().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cmbOrganizacao;
    private javax.swing.JTextField cmbStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tabelaVagas;
    private javax.swing.JTextField txtCargaHoras;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtNumeroVagas;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables

    private void carregarTabela() {
        try {

            List<Vaga> vagas = dao.listar();

            DefaultTableModel modelo = (DefaultTableModel) tabelaVagas.getModel();

            modelo.setRowCount(0);

            SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");

            for (Vaga vaga : vagas) {

                modelo.addRow(new Object[]{
                    vaga.getId(),
                    vaga.getTitulo(),
                    vaga.getDescricao(),
                    vaga.getCargahoras(),
                    vaga.getNumerovagas(),
                    formato.format(vaga.getDatavaga()),
                    vaga.getStatus(),
                    vaga.getIdOrganizacao()
                });
            }

        } catch (SQLException e) {

            JOptionPane.showMessageDialog(this,
                    "Erro ao carregar vagas:\n"
                    + e.getMessage());
        }

    }

    private void limparCampos() {

        idSelecionado = 0;

        txtTitulo.setText("");
        txtDescricao.setText("");
        txtCargaHoras.setText("");
        txtNumeroVagas.setText("");
        txtData.setText("");
        cmbStatus.setText("");

        if (cmbOrganizacao.getItemCount() > 0) {
            cmbOrganizacao.setSelectedIndex(0);
        }

        tabelaVagas.clearSelection();

    }

    private void carregarOrganizacoes() {
        try {

            List<Organizacao> organizacoes = organizacaoDAO.listar();

            cmbOrganizacao.removeAllItems();

            for (Organizacao organizacao : organizacoes) {

                cmbOrganizacao.addItem(organizacao.getNome());

            }

        } catch (SQLException e) {

            JOptionPane.showMessageDialog(this,
                    "Erro ao carregar organizações:\n"
                    + e.getMessage());
        }

    }

    private void selecionarOrganizacao(int idOrganizacao) {
        try {

            List<Organizacao> organizacoes = organizacaoDAO.listar();

            for (Organizacao organizacao : organizacoes) {

                if (organizacao.getId() == idOrganizacao) {

                    cmbOrganizacao.setSelectedItem(organizacao.getNome());

                    return;
                }
            }

        } catch (SQLException e) {

            JOptionPane.showMessageDialog(this,
                    "Erro ao selecionar organização:\n"
                    + e.getMessage());
        }

    }

    private int buscarIdOrganizacao(String nomeOrganizacao) {

        try {

            List<Organizacao> organizacoes = organizacaoDAO.listar();

            for (Organizacao organizacao : organizacoes) {

                if (organizacao.getNome().equals(nomeOrganizacao)) {

                    return organizacao.getId();

                }
            }

        } catch (SQLException e) {

            JOptionPane.showMessageDialog(this,
                    "Erro ao buscar organização:\n"
                    + e.getMessage());
        }

        return 0;
    }

}
